idx_width: 38
idx_middle: 968
height_idx_low: 0
height_idx_up: 10
min_ang_idx: 0
 
laser_offset_x: -0.02
laser_offset_y: 0.07
laser_offset_z: 0.273
 
occ_res: 0.05
cloud_res: 0.05
shift_yaw: 0.7854

min_theta: -1.5708

max_angular_correction_deg: 25
max_linear_correction: 0.5
max_iterations: 10
epsilon_xy: 0.001
epsilon_theta: 0.01
max_correspondence_dist: 0.3
do_compute_covariance: 1
outliers_maxPerc: 0.9
outliers_adaptive_order: 0.7

decay_rate: 99
frame_id: map
